"""empty message

Revision ID: 4faa2aaa0156
Revises: 8eeeda1f95e5
Create Date: 2024-02-23 14:21:21.540488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4faa2aaa0156'
down_revision = '8eeeda1f95e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacations_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('traveler_id', sa.Integer(), nullable=True),
    sa.Column('island_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['island_id'], ['islands_table.id'], name=op.f('fk_vacations_table_island_id_islands_table')),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers_table.id'], name=op.f('fk_vacations_table_traveler_id_travelers_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacations_table')
    # ### end Alembic commands ###
